language: php

php:
  - 7.0

sudo: false

env:
  global:
    - DEFAULT=1
    - secure: j+1g/twymlVnvpQlsdS+82IY3xR8GIBB7m8bEmpYP6J1ketRToJWANDre6Xb/33JHEzekcr5Kt0F2UDkNzR5rNbviHqYH4EyHA7VZTikqSSelY+lZF7qo1xTyGRnCJZV6c2bri/rPVSjw1FYngNFh5FGCh7PmpzzeQZkhyCG3Cs=

matrix:
  fast_finish: true

  include:
    - php: 7
      env: PHPCS=1 DEFAULT=0

    - php: 7
      env: COVERALLS=1 DEFAULT=0

install:
  - composer self-update
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer install --prefer-dist --no-interaction --dev

before_script:
  - sh -c "if [ '$PHPCS' = '1' ]; then composer require squizlabs/php_codesniffer:dev-master; fi"

  - sh -c "if [ '$COVERALLS' = '1' ]; then composer require --dev satooshi/php-coveralls:dev-master; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then mkdir -p build/logs; fi"

script:
  - sh -c "if [ '$COVERALLS' = '1' ]; then phpunit --stderr --coverage-clover build/logs/clover.xml; fi"
  - sh -c "if [ '$COVERALLS' = '1' ]; then php vendor/bin/coveralls -v; fi"
  - sh -c "if [ '$DEFAULT' = '1' ]; then phpunit --stderr; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then ./vendor/bin/phpcs -n -p --extensions=php --standard=PSR2 --ignore=vendor --ignore=tests . ; fi"

notifications:
  email: false
