language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2

env:
  global:
    - DEFAULT=1
    - secure: j+1g/twymlVnvpQlsdS+82IY3xR8GIBB7m8bEmpYP6J1ketRToJWANDre6Xb/33JHEzekcr5Kt0F2UDkNzR5rNbviHqYH4EyHA7VZTikqSSelY+lZF7qo1xTyGRnCJZV6c2bri/rPVSjw1FYngNFh5FGCh7PmpzzeQZkhyCG3Cs=

matrix:
  fast_finish: true
  allow_failures:
      - php: 7.2

before_install:
  - composer self-update
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

install:
  - composer install --prefer-dist --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/php-cs-fixer fix --diff --dry-run
  - vendor/bin/phpcs -s --config-set ignore_warnings_on_exit 1
  - vendor/bin/phpunit --stderr --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/codacycoverage clover build/coverage/xml

notifications:
  email: false
